require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

pre_install do |installer|
Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'farmaciamaisproxima' do
  config = use_native_modules!
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  use_react_native!(:path => config["reactNativePath"])
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"  

  target 'farmaciamaisproximaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.96.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'farmaciamaisproxima-tvOS' do
  # Pods for farmaciamaisproxima-tvOS

  target 'farmaciamaisproxima-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
